### PR TITLE
Fixed websocket reference cycle

### PR DESCRIPTION
**Pull request by grahamburgsma**
Websockets aren't being deallocated

### CODE REVIEW

**Comment by grahamburgsma** [comment]
Note: 1 test is failing, but not because of my changes.

**Comment by calebkleveter** [comment]
Nice! Could you add a test case so we can make sure this doesn't happen in the future?

**Comment by grahamburgsma** [comment]
Added a test @calebkleveter. I don't write many tests, but it appears to verify the fix. Let me know if you have any suggestions.

**Comment by penny-coin** [comment]
Hey @grahamburgsma, you just merged a pull request, have a coin! 

You now have 2 coins.

**Pull request merged**
